Added Example for DevExpress Support
My Prism custom Region Adapter for DX:RibbonControl fails when more than 1 RibbonPage tab is added.

Error: 'Element with the same name already exists in the scope'